name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: install
      run: yarn install
    - name: build
      run: yarn build
      
    - name: S3 update
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env: 
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: './public'
        
    - name: Create Invalidation for CloudFront
      uses: awact/cloudfront-action@master
      env: 
        SOURCE_DIR: './public'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
